version: '3.8'

services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: "Password2024"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "HrSystemApp"
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: eslammoataz/hrms-backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=HrSystemApp;Username=admin;Password=Password2024
    depends_on:
      - database

volumes:
  pgdata: