version: '3.8'

services:
  database:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "Password2024"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "HrSystemApp"
    ports:
      - "5444:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d HrSystemApp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # seq:
  #   image: datalust/seq:latest
  #   restart: always
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SEQ_FIRSTRUN_ADMINPASSWORD=Password2024!
  #   ports:
  #     - "5341:80"
  #   volumes:
  #     - seqdata_dev:/data

  minio:
    image: minio/minio:latest
    container_name: minio-dev
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "Password2024!"
    volumes:
      - miniodata_dev:/data
    command: server /data --console-address ":9001"

volumes:
  pgdata_dev:
  # seqdata_dev:
  miniodata_dev: