version: '3.8'

services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: "Password2024"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "HrSystemApp"
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: eslammoataz/hrms-backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=HrSystemApp;Username=admin;Password=Password2024
      - DataProtection__KeysPath=/var/app/dpkeys
      - DataProtection__ApplicationName=HrSystemApp
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=minioadmin
      - Minio__SecretKey=minioadmin
      - Minio__UseSsl=false
    depends_on:
      - database
      - minio
    volumes:
      - dpkeys:/var/app/dpkeys

  minio:
    image: quay.io/minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  seq:
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=Password2024!
    ports:
      - "5341:80"
    volumes:
      - seqdata:/data

volumes:
  pgdata:
  seqdata:
  dpkeys:
  minio_data: